apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: royalwheels
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'royalwheels'
        metrics_path: /metrics
        static_configs:
          - targets: ['royalwheels-service:80']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: royalwheels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.50.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: royalwheels
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: web
  selector:
    app: prometheus
