apiVersion: v1
kind: Secret
metadata:
  name: royalwheels-secrets
  namespace: royalwheels
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-me-to-a-secure-secret-key"
  DATABASE_URL: "postgres://royaladmin:KFwsn8)khyfR&Yfs+4Y_p1hm@royalwheels-postgres.cdsui6cggnep.ap-south-1.rds.amazonaws.com:5432/royalwheels"
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  EMAIL_HOST_USER: "royalwheel342@gmail.com"
  EMAIL_HOST_PASSWORD: ""
  CLOUDINARY_URL: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
