apiVersion: v1
kind: Service
metadata:
  name: royalwheels-service
  namespace: royalwheels
  labels:
    app: royalwheels
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: royalwheels
